// auth
export const LOGIN_USER = "LOGIN_USER";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const CHECK_LINK_SUCCESS = "CHECK_LINK_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const GET_NOTIFICATIONS_LIST_RESPONSE =
  "GET_NOTIFICATIONS_LIST_RESPONSE";
export const READ_NOTIFICATIONS_RESPONSE = "READ_NOTIFICATIONS_RESPONSE";
export const SET_UNREAD_MESSAGE_COUNT = "SET_UNREAD_MESSAGE_COUNT";
export const DASHBOARD_COUNT_RESPONSE = "DASHBOARD_COUNT_RESPONSE";

//User

export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const ACTIVE_DEACTIVE_USER_SUCCESS = "ACTIVE_DEACTIVE_USER_SUCCESS";
export const GET_ALL_USER_BY_ID = "GET_ALL_USER_BY_ID";
export const DELETE_LOAD_SUCCESS = "DELETE_LOAD_SUCCESS";

//Blog Post
export const ADD_BLOG_POST_DETAILS_SUCCESS = "ADD_BLOG_POST_DETAILS_SUCCESS";
export const GET_BLOG_POST_DETAILS_SUCCESS = "GET_BLOG_POST_DETAILS_SUCCESS";
export const ACTIVE_DEACTIVE_BLOG_POST_SUCCESS =
  "ACTIVE_DEACTIVE_BLOG_POST_SUCCESS";
export const GET_ALL_BLOG_POST_BY_ID = "GET_ALL_BLOG_POST_BY_ID";
export const EDIT_BLOG_POST_DETAILS_SUCCESS = "EDIT_BLOG_POST_DETAILS_SUCCESS";
export const DELETE_BLOG_POST_SUCCESS = "DELETE_BLOG_POST_SUCCESS";

//Bulletin
export const ADD_BULLETIN_DETAILS_SUCCESS = "ADD_BULLETIN_DETAILS_SUCCESS";
export const GET_BULLETIN_DETAILS_SUCCESS = "GET_BULLETIN_DETAILS_SUCCESS";
export const ACTIVE_DEACTIVE_BULLETIN_SUCCESS =
  "ACTIVE_DEACTIVE_BULLETIN_SUCCESS";
export const GET_ALL_BULLETIN_BY_ID = "GET_ALL_BULLETIN_BY_ID";
export const EDIT_BULLETIN_DETAILS_SUCCESS = "EDIT_BULLETIN_DETAILS_SUCCESS";
export const DELETE_BULLETIN_SUCCESS = "DELETE_BULLETIN_SUCCESS";
//Page
export const ADD_PAGE_DETAILS_SUCCESS = "ADD_PAGE_DETAILS_SUCCESS";
export const GET_PAGE_DETAILS_SUCCESS = "GET_PAGE_DETAILS_SUCCESS";
export const ACTIVE_DEACTIVE_PAGE_SUCCESS = "ACTIVE_DEACTIVE_PAGE_SUCCESS";
export const GET_ALL_PAGE_BY_ID = "GET_ALL_PAGE_BY_ID";
export const EDIT_PAGE_DETAILS_SUCCESS = "EDIT_PAGE_DETAILS_SUCCESS";
export const DELETE_PAGE_SUCCESS = "DELETE_PAGE_SUCCESS";

//Program
export const ADD_PROGRAM_DETAILS_SUCCESS = "ADD_PROGRAM_DETAILS_SUCCESS";
export const GET_PROGRAM_DETAILS_SUCCESS = "GET_PROGRAM_DETAILS_SUCCESS";
export const ACTIVE_DEACTIVE_PROGRAM_SUCCESS =
  "ACTIVE_DEACTIVE_PROGRAM_SUCCESS";
export const GET_ALL_PROGRAM_BY_ID = "GET_ALL_PROGRAM_BY_ID";
export const EDIT_PROGRAM_DETAILS_SUCCESS = "EDIT_PROGRAM_DETAILS_SUCCESS";
export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const PROGRAM_FEEDBACK = "PROGRAM_FEEDBACK";

// Settings
export const GET_SETTINGS_DETAILS = "GET_SETTINGS_DETAILS";
export const EDIT_SETTINGS_DETAILS_SUCCESS = "EDIT_SETTINGS_DETAILS_SUCCESS";

//APPOINTEMENT
export const ADD_APPOINTEMENT_DETAILS_SUCCESS =
  "ADD_APPOINTEMENT_DETAILS_SUCCESS";
export const GET_APPOINTEMENT_DETAILS_SUCCESS =
  "GET_APPOINTEMENT_DETAILS_SUCCESS";
export const ACTIVE_DEACTIVE_APPOINTEMENT_SUCCESS =
  "ACTIVE_DEACTIVE_APPOINTEMENT_SUCCESS";
export const GET_ALL_APPOINTEMENT_BY_ID = "GET_ALL_APPOINTEMENT_BY_ID";
export const EDIT_APPOINTEMENT_DETAILS_SUCCESS =
  "EDIT_APPOINTEMENT_DETAILS_SUCCESS";
export const DELETE_APPOINTEMENT_SUCCESS = "DELETE_APPOINTEMENT_SUCCESS";

// App Redux Action Types
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";

// Agency Sidebar
export const AGENCY_TOGGLE_MENU = "AGENCY_TOGGLE_MENU";
export const CHANGE_AGENCY_LAYOUT_BG = "CHANGE_AGENCY_LAYOUT_BG";

// sidebar
export const TOGGLE_MENU = "TOGGLE_MENU";

//Commitment
export const GET_PROGRAM_STAGE_LIST_SUCCESS = "GET_PROGRAM_STAGE_LIST_SUCCESS";
export const DELETE_PROGRAM_STAGE_SUCCESS = "DELETE_PROGRAM_STAGE_SUCCESS";
export const GET_PROGRAM_STAGE_SUCCESS = "GET_PROGRAM_STAGE_SUCCESS";
export const ADD_COMMITMENT_STAGE_SUCCESS = "ADD_COMMITMENT_STAGE_SUCCESS";
export const EDIT_COMMITMENT_STAGE_SUCCESS = "EDIT_COMMITMENT_STAGE_SUCCESS";
export const ADD_STAGE_CATEGORY_SUCCESS = "ADD_STAGE_CATEGORY_SUCCESS";
export const EDIT_STAGE_CATEGORY_SUCCESS = "EDIT_STAGE_CATEGORY_SUCCESS";
export const DELETE_STAGE_CATEGORY_SUCCESS = "DELETE_STAGE_CATEGORY_SUCCESS";
export const ADD_STAGE_SUB_CATEGORY_SUCCESS = "ADD_STAGE_SUB_CATEGORY_SUCCESS";
export const EDIT_STAGE_SUB_CATEGORY_SUCCESS =
  "EDIT_STAGE_SUB_CATEGORY_SUCCESS";
export const DELETE_STAGE_SUB_CATEGORY_SUCCESS =
  "DELETE_STAGE_SUB_CATEGORY_SUCCESS";
export const ADD_SUPPORTING_MATERIAL_SUCCESS =
  "ADD_SUPPORTING_MATERIAL_SUCCESS";
export const GET_SUPPORTING_MATERIAL_SUCCESS =
  "GET_SUPPORTING_MATERIAL_SUCCESS";
export const EDIT_SUPPORTING_MATERIAL_SUCCESS =
  "EDIT_SUPPORTING_MATERIAL_SUCCESS";
export const DELETE_SUPPORTING_MATERIAL_SUCCESS =
  "DELETE_SUPPORTING_MATERIAL_SUCCESS";

// feedback and support
export const GET_SUPPORT_AND_FEEDBACK_LIST_SUCCESS =
  "GET_SUPPORT_AND_FEEDBACK_LIST_SUCCESS";
